export const CDP_CONNECTION_TIMEOUT = 15000; // 15 sec
export const CDP_CONNECTION_RETRIES = 3;
export const CDP_CONNECTION_RETRY_BASE_DELAY = 500;
export const CDP_REQUEST_TIMEOUT = 15000; // 15 sec
export const CDP_REQUEST_RETRIES = 3;
export const CDP_REQUEST_RETRY_BASE_DELAY = 500;
