export const ANALYSIS_POLICY_V1 = Object.freeze({
    version: 1,
    longRun: { thresholdMs: 20 * 60 * 1000 },
    majorPhase: {
        minWallMs: 1000,
        minRunShare: 0.1,
        minListenerWallMs: 100,
        minListenerShare: 0.05,
        maxListeners: 3,
    },
    eventListener: {
        minSingleWallMs: 100,
        minTotalWallMs: 500,
        minRunShare: 0.05,
        minMeanWallMs: 100,
    },
    testFile: { minWallMs: 250, minGroupShare: 0.1 },
    slowTest: { minWallMs: 10000, minExecutionShare: 0.05, minMeanMultiple: 3, minSampleForRelative: 5 },
    commonHook: { minTotalWallMs: 1000, minCalls: 10, minExecutionShare: 0.1, minMeanWallMs: 10000 },
    command: { minWallMs: 10000, minExecutionShare: 0.05, minMeanWallMs: 3000 },
    pause: { minTotalWallMs: 5000, minCalls: 3, minSingleWallMs: 5000, minShare: 0.1 },
    unattributed: { minWallMs: 2000, minShare: 0.15 },
    workers: {
        minExecutionMs: 10000,
        minMedianWorkerEventLoopUtilization: 0.8,
        minSustainedEventLoopDelayMs: 50,
        minConcurrentCallOverlapMs: 1000,
        minConcurrentCallOverlapShare: 0.1,
        maxHostCpu95thPercentile: 0.75,
    },
    sessions: {
        minAttempts: 20,
        minLimitSaturationShare: 0.3,
        minTailMs: 5000,
        minTailShare: 0.1,
    },
    hostCpu: { high95thPercentile: 0.85 },
    resources: { minSamples: 20, healthyMedianEventLoopDelayMs: 20 },
});
