import { sortedLastIndex, memoize } from "lodash";
import { TraceMap, eachMapping, type EncodedSourceMap } from "@jridgewell/trace-mapping";
import fs from "fs";
import path from "path";
import { URL } from "url";
import * as logger from "../../../utils/logger";
import type { CDPRuntime } from "../domains/runtime";
import type { CDPScriptCoverage, CDPSessionId } from "../types";
import { softFileURLToPath } from "../../../utils/fs";
import type {
    CachedOnFs,
    HashFileContents,
    NormalizedDependencies,
    SelectivityCompressionType,
    TestDependenciesFileContents,
} from "./types";
import { WEBPACK_PROTOCOL } from "./constants";
import { readJsonWithCompression } from "./json-utils";
import type { Test } from "../../../types";
import {
    SelectivityDependencyReason,
    SelectivityDependencyScope,
    SelectivityMapDependencyRelativePathFn,
} from "../../../config/types";
import { CacheType, getCachedSelectivityFile, setCachedSelectivityFile } from "./fs-cache";

/**
 * Sorted list of generated-bundle segment boundaries.
 * Segment `i` owns generated bytes `[offset[i], offset[i + 1])` (the last segment runs to the end of the bundle)
 */
interface ParsedSourceMapRanges {
    offset: number[];
    /** Can be empty if segment is glue code */
    filename: string[];
}

/**
 * Tries to fetch text by url from node.js, then falls back to "fetch" from browser, if node.js fetch fails
 * @param url text url
 * @param runtime CDP runtime domain
 * @param sessionId CDP session id
 * @returns text
 */
export const fetchTextWithBrowserFallback = async (
    url: string,
    runtime: CDPRuntime,
    sessionId: CDPSessionId,
): Promise<string> => {
    const isSourceMapEmbedded = new URL(url).protocol === "data:";

    if (isSourceMapEmbedded) {
        // With "data" protocol it just decodes embedded source maps without actual network requests
        // So we can do it directly from node.js
        return fetch(url).then(r => r.text());
    }

    // At first, trying to fetch sourceMaps directly from the node.js
    // Then falling back to do it via browser (if Testplane has no direct network access to it, for example)
    try {
        return await fetch(url).then(r => r.text());
    } catch {
        return runtime
            .evaluate<string>(sessionId, {
                expression: `fetch("${url.replaceAll('"', '\\"')}").then(r => r.text())`,
                awaitPromise: true,
                returnByValue: true,
            })
            .then(r => r.result.value);
    }
};

const isWebpackProtocol = (posixRelativeSourceFilePath: string): boolean => {
    return posixRelativeSourceFilePath.startsWith(WEBPACK_PROTOCOL);
};

/**
 * Replaces "webpack://" protocol with source path because "source-map" doesn't work well with protocol paths
 * @param sourceMap Raw source maps in https://tc39.es/ecma426/ format
 * @param sourceRoot Source root
 */
export const patchSourceMapSources = (sourceMap: EncodedSourceMap, sourceRoot?: string): EncodedSourceMap => {
    sourceMap.sourceRoot = sourceRoot || sourceMap.sourceRoot;

    for (let i = 0; i < sourceMap.sources.length; i++) {
        if (sourceMap.sources[i] && isWebpackProtocol(sourceMap.sources[i] as string)) {
            sourceMap.sources[i] = (sourceMap.sources[i] as string).slice(WEBPACK_PROTOCOL.length);
        }
    }

    return sourceMap;
};

const getSourceLineOffsetArray = (source: string): number[] => {
    let sourceOffset = source.indexOf("\n");
    const offsetToLine = [0];

    while (sourceOffset !== -1) {
        offsetToLine.push(++sourceOffset);
        sourceOffset = source.indexOf("\n", sourceOffset);
    }

    return offsetToLine;
};

export const parseSourceMapRanges = async (
    source: string,
    sourceMaps: string,
    sourceRoot: string,
): Promise<ParsedSourceMapRanges> => {
    let jsonCachedResult: ParsedSourceMapRanges | null = null;

    try {
        const cachedResult = await getCachedSelectivityFile(CacheType.SourceMapParseResult, sourceMaps);
        jsonCachedResult = cachedResult ? JSON.parse(cachedResult) : null;
    } catch {} // eslint-disable-line no-empty

    if (jsonCachedResult) {
        return jsonCachedResult;
    }

    const lineOffsetArray = getSourceLineOffsetArray(source);
    const sourceMapsParsed = patchSourceMapSources(JSON.parse(sourceMaps), sourceRoot);
    const traceMap = new TraceMap(sourceMapsParsed);

    const result: ParsedSourceMapRanges = {
        offset: [],
        filename: [],
    };

    // "eachMapping" walks segments in generated order (line asc, then column asc).
    // A single source can still appear in several disjoint segments (bundlers interleave/concatenate modules),
    let lastRecordedSource: string | undefined;
    eachMapping(traceMap, mapping => {
        const mappingSource = mapping.source || "";
        const lineOffset = lineOffsetArray[mapping.generatedLine - 1];

        // Skip out-of-range
        if (typeof lineOffset === "undefined") {
            return;
        }

        if (mappingSource === lastRecordedSource) {
            return;
        }

        result.offset.push(lineOffset + mapping.generatedColumn);
        result.filename.push(mappingSource);
        lastRecordedSource = mappingSource;
    });

    setCachedSelectivityFile(CacheType.SourceMapParseResult, sourceMaps, JSON.stringify(result)).catch(() => {});

    return result;
};

/**
 * Given compiled code, its source map, and the executed offsets
 * It returns the original source files touched
 * Useful for turning coverage ranges into real TS/JS module dependencies
 * @param source Compiled source code
 * @param sourceMaps Source maps JSON string
 * @param coverages CDP script coverages
 * @param sourceRoot Source root
 */
export const extractSourceFilesDeps = (
    { offset, filename }: ParsedSourceMapRanges,
    coverages: CDPScriptCoverage[],
    sourceFilterFn?: (sourceFileName: string) => boolean,
): Set<string> => {
    const dependantSourceFiles = new Set<string>();

    if (!offset.length) {
        return dependantSourceFiles;
    }

    for (const scriptCoverage of coverages) {
        for (const functionCall of scriptCoverage.functions) {
            // ranges[0] is the function's full extent in V8 coverage; nested ranges are sub-blocks
            const range = functionCall.ranges[0];

            if (!range || !range.count) {
                continue;
            }

            // Ignore full-file wrapper
            if (range.startOffset <= offset[0] && range.endOffset >= offset[offset.length - 1]) {
                const filesCount = filename.reduce((acc, val) => acc + (val ? 1 : 0), 0);

                if (filesCount > 2) {
                    continue;
                }
            }

            const startIdx = Math.max(0, sortedLastIndex(offset, range.startOffset) - 1);

            for (let idx = startIdx; idx < offset.length && offset[idx] < range.endOffset; idx++) {
                const sourceFile = filename[idx];

                if (sourceFile && (!sourceFilterFn || sourceFilterFn(sourceFile))) {
                    dependantSourceFiles.add(sourceFile);
                }
            }
        }
    }

    return dependantSourceFiles;
};

/**
 * @returns True, if fileUrlLikePath has some kind of protocol ("data://", "webpack://", "turbopack://", "file://")...
 */
export const hasProtocol = (fileUrlLikePath: string): boolean => {
    if (!fileUrlLikePath.includes("://")) {
        return false;
    }

    try {
        return Boolean(new URL(fileUrlLikePath).protocol);
    } catch {
        return false;
    }
};

const getProtocol = (fileUrlLikePath: string): string | null => {
    if (!fileUrlLikePath.includes("://")) {
        return null;
    }

    try {
        return new URL(fileUrlLikePath).protocol;
    } catch {
        return null;
    }
};

export const isDataProtocol = (fileUrlLikePath: string): boolean => fileUrlLikePath.startsWith("data:");

const ensurePosixRelativeDependencyPathExists = (posixRelativePath: string): void => {
    const relativePath = posixRelativePath.replaceAll(path.posix.sep, path.sep);

    if (fs.existsSync(relativePath)) {
        return;
    }

    throw new Error(
        [
            `Selectivity: Couldn't find "${relativePath}", which is test's dependency`,
            "Please ensure 'sources' of generated source maps contain valid paths to existing files",
            "Configuring 'sourceRoot' in Testplane selectivity config also might help",
        ].join("\n"),
    );
};

const warnUnsupportedProtocol = memoize((protocol: string, dependency: string): void => {
    logger.warn(`Selectivity: Ignoring dependencies of unsupported protocol "${protocol}" (example: "${dependency}")`);
});

/**
 * @param dependencies.css set of css dependency URI's
 * @param dependencies.js set of js dependency URI's
 * @param dependencies.png set of png dependency URI's
 * @returns sorted uniq arrays of relative paths
 */
export const transformSourceDependencies = (
    {
        css: cssDependencies,
        js: jsDependencies,
        png: pngDependencies,
    }: { css: Set<string> | null; js: Set<string> | null; png: Set<string> | null },
    mapDependencyPathFn: null | SelectivityMapDependencyRelativePathFn,
    scope: SelectivityDependencyScope,
): NormalizedDependencies => {
    const nodeModulesLabel = "node_modules/";
    const cssSet: Set<string> = new Set();
    const jsSet: Set<string> = new Set();
    const modulesSet: Set<string> = new Set();
    const pngSet: Set<string> = new Set();

    const classifyDependency = (
        dependency: string,
        typedResultSet: Set<string>,
        reason: SelectivityDependencyReason,
    ): void => {
        dependency = decodeURIComponent(softFileURLToPath(dependency));

        const protocol = getProtocol(dependency);

        if (protocol) {
            warnUnsupportedProtocol(protocol, dependency);
            return;
        }

        const initialDependencyRelativePath = path.posix.relative(path.posix.resolve(), path.posix.resolve(dependency));
        const mapDependencyPathResult = mapDependencyPathFn
            ? mapDependencyPathFn({
                  scope,
                  reason,
                  relativePath: initialDependencyRelativePath,
              })
            : true;

        if (!mapDependencyPathResult) {
            return;
        }

        const dependencyRelativePath =
            mapDependencyPathResult === true ? initialDependencyRelativePath : mapDependencyPathResult;
        const nodeModulesLabelPos = dependencyRelativePath.indexOf(nodeModulesLabel);

        if (nodeModulesLabelPos === -1) {
            ensurePosixRelativeDependencyPathExists(dependencyRelativePath);
            typedResultSet.add(dependencyRelativePath);
            return;
        }

        const modulePos = nodeModulesLabelPos + nodeModulesLabel.length;
        const isScopedDependency = dependencyRelativePath[modulePos] === "@";
        let moduleEndPos;

        if (isScopedDependency) {
            const scopeEndPos = dependencyRelativePath.indexOf("/", modulePos + 1);

            moduleEndPos = scopeEndPos === -1 ? -1 : dependencyRelativePath.indexOf("/", scopeEndPos + 1);
        } else {
            moduleEndPos = dependencyRelativePath.indexOf("/", modulePos + 1);
        }

        if (moduleEndPos === -1) {
            ensurePosixRelativeDependencyPathExists(dependencyRelativePath);
            typedResultSet.add(dependencyRelativePath);
        } else {
            const modulePath = dependencyRelativePath.slice(0, moduleEndPos);

            ensurePosixRelativeDependencyPathExists(modulePath);

            modulesSet.add(modulePath);
        }
    };

    if (cssDependencies) {
        for (const cssDependency of cssDependencies.values()) {
            // Testplane can't have css dependencies
            classifyDependency(cssDependency, cssSet, "browser-css-import");
        }
    }

    if (jsDependencies) {
        for (const jsDependency of jsDependencies.values()) {
            classifyDependency(
                jsDependency,
                jsSet,
                scope === "browser" ? "browser-js-coverage" : "testplane-js-import",
            );
        }
    }

    if (pngDependencies) {
        for (const pngDependency of pngDependencies.values()) {
            // Browser png dependencies are not tracked
            classifyDependency(pngDependency, pngSet, "testplane-assert-view-reference");
        }
    }

    const cmpStr = (a: string, b: string): number => a.localeCompare(b);

    return {
        css: Array.from(cssSet).sort(cmpStr),
        js: Array.from(jsSet).sort(cmpStr),
        modules: Array.from(modulesSet).sort(cmpStr),
        png: Array.from(pngSet).sort(cmpStr),
    };
};

/** Merges two sorted deps array into one with uniq values */
export const mergeSourceDependencies = (
    a: NormalizedDependencies,
    b: NormalizedDependencies,
): NormalizedDependencies => {
    const result: NormalizedDependencies = { css: [], js: [], modules: [], png: [] };

    for (const depType of Object.keys(result) as Array<keyof NormalizedDependencies>) {
        let aInd = 0,
            bInd = 0;

        if (!a[depType]) {
            if (!b[depType]) {
                continue;
            }

            result[depType] = b[depType];

            continue;
        } else if (!b[depType]) {
            result[depType] = a[depType];

            continue;
        }

        while (aInd < a[depType].length || bInd < b[depType].length) {
            let compareResult;

            if (bInd >= b[depType].length) {
                compareResult = -1;
            } else if (aInd >= a[depType].length) {
                compareResult = 1;
            } else {
                compareResult = a[depType][aInd].localeCompare(b[depType][bInd]);
            }

            if (compareResult < 0) {
                result[depType].push(a[depType][aInd]);

                do {
                    aInd++;
                } while (a[depType][aInd] === a[depType][aInd - 1]);
            } else if (compareResult > 0) {
                result[depType].push(b[depType][bInd]);

                do {
                    bInd++;
                } while (b[depType][bInd] === b[depType][bInd - 1]);
            } else {
                result[depType].push(a[depType][aInd]);

                do {
                    aInd++;
                } while (a[depType][aInd] === a[depType][aInd - 1]);

                do {
                    bInd++;
                } while (b[depType][bInd] === b[depType][bInd - 1]);
            }
        }
    }

    return result;
};

// Ensures file consistency
export const shallowSortObject = (obj: Record<string, unknown>): void => {
    const testBrowsers = Object.keys(obj).sort((a, b) => a.localeCompare(b));

    for (const testBrowser of testBrowsers) {
        const testBrowserDeps = obj[testBrowser];

        delete obj[testBrowser];

        obj[testBrowser] = testBrowserDeps;
    }
};

export const getSelectivityHashesPath = (testDependenciesPath: string): string =>
    path.join(testDependenciesPath, "hashes.json");

export const readHashFileContents = (
    selectivityHashesPath: string,
    compression: SelectivityCompressionType,
): Promise<HashFileContents> =>
    readJsonWithCompression(selectivityHashesPath, compression, {
        defaultValue: { files: {}, modules: {}, patterns: {} },
    })
        .catch(() => ({ files: {}, modules: {}, patterns: {} }))
        .then(res => {
            res.files ||= {};
            res.modules ||= {};
            res.patterns ||= {};

            return res;
        });

export const getSelectivityTestsPath = (testDependenciesPath: string): string =>
    path.join(testDependenciesPath, "tests");

export const getTestSelectivityDumpId = (test: Test): string => test.id;

export const getTestDependenciesPath = (selectivityTestsPath: string, test: Test): string =>
    path.join(selectivityTestsPath, `${getTestSelectivityDumpId(test)}.json`);

/** @returns `Promise<Record<BrowserID, Record<DepType, NormalizedDependencies>>>` */
export const readTestDependencies = async (
    selectivityTestsPath: string,
    test: Test,
    compression: SelectivityCompressionType,
): Promise<TestDependenciesFileContents> => {
    const result = (await readJsonWithCompression(getTestDependenciesPath(selectivityTestsPath, test), compression, {
        defaultValue: {},
    }).catch(() => ({}))) as Record<
        string,
        Record<string, Partial<NormalizedDependencies> & Pick<NormalizedDependencies, "css" | "js" | "modules" | "png">>
    >;

    for (const browserId in result) {
        for (const depType in result[browserId]) {
            const currentDeps = result[browserId][depType];

            currentDeps.css ||= [];
            currentDeps.js ||= [];
            currentDeps.modules ||= [];
            currentDeps.png ||= [];
        }
    }

    return result;
};

export const isCachedOnFs = (value: unknown): value is CachedOnFs => value === true;
