export const BIDI_CONNECTION_TIMEOUT = 15000; // 15 sec
export const BIDI_CONNECTION_RETRIES = 3;
export const BIDI_CONNECTION_RETRY_BASE_DELAY = 500;
export const BIDI_REQUEST_RETRIES = 3;
export const BIDI_REQUEST_RETRY_BASE_DELAY = 500;
