export const customCommandFileNames = [
    "assert-view",
    "clearSession",
    "getConfig",
    "getPuppeteer",
    "setOrientation",
    "scrollIntoView",
    "openAndWait",
    "switchToRepl",
    "moveCursorTo",
    "captureDomSnapshot",
    "waitForStaticToLoad",
    "saveState",
    "restoreState",
    "getState",
    "unstable_getCdp",
];
