name: Standalone Browser Integration Tests

on:
    pull_request:
        branches: [master]

jobs:
    integration-test:
        runs-on: ubuntu-latest
        env:
            DOCKER_IMAGE_NAME: html-reporter-browsers

        strategy:
            matrix:
                node-version: [24.x]
                browser: [chrome, firefox]

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: Cache Testplane browsers and drivers
              uses: actions/cache@v3
              with:
                  path: ~/.testplane
                  key: ${{ runner.os }}-testplane-${{ matrix.browser }}
                  restore-keys: |
                      ${{ runner.os }}-testplane-${{ matrix.browser }}-
                      ${{ runner.os }}-testplane-

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build

            - name: "Prepare screenshot tests: Cache browser docker image"
              if: ${{ matrix.browser == 'chrome' }}
              uses: actions/cache@v3
              with:
                  path: ~/.docker/cache
                  key: docker-browser-image-testplane

            - name: "Prepare screenshot tests: Pull browser docker image"
              if: ${{ matrix.browser == 'chrome' }}
              run: |
                  mkdir -p ~/.docker/cache
                  if [ -f ~/.docker/cache/image.tar ]; then
                    docker load -i ~/.docker/cache/image.tar
                  else
                    docker pull yinfra/html-reporter-browsers
                    docker save yinfra/html-reporter-browsers -o ~/.docker/cache/image.tar
                  fi

            - name: "Prepare screenshot tests: Run browser docker image"
              if: ${{ matrix.browser == 'chrome' }}
              run: docker run -d --name ${{ env.DOCKER_IMAGE_NAME }} -it --rm --network=host $(which colima >/dev/null || echo --add-host=host.docker.internal:0.0.0.0) yinfra/html-reporter-browsers

            - name: Run integration tests for ${{ matrix.browser }}
              env:
                  BROWSER: ${{ matrix.browser }}
              run: npm run test-integration

            - name: "Screenshot tests: Stop browser docker image"
              if: ${{ always() && matrix.browser == 'chrome' }}
              run: |
                  docker kill ${{ env.DOCKER_IMAGE_NAME }} || true
                  docker rm ${{ env.DOCKER_IMAGE_NAME }} || true
