import url from "node:url";
import path from "node:path";
import _ from "lodash";

import { VITE_RUN_UUID_ROUTE, WORKER_ENV_BY_RUN_UUID } from "./constants";

import type { Connect } from "vite";
import type { WorkerInitializePayload } from "./browser-modules/types";

type TestInfoFromViteRequest = {
    routeName: string;
    runUuid: string;
    env: WorkerInitializePayload;
};

// TODO: use import.meta.url after migrate to esm
export const getImportMetaUrl = (path: string): string => {
    return url.pathToFileURL(path).toString();
};

// TODO: use from browser code after migrate to esm
export const prepareError = (error: Error): Error => {
    return JSON.parse(JSON.stringify(error, Object.getOwnPropertyNames(error)));
};

export const getTestInfoFromViteRequest = (req: Connect.IncomingMessage): TestInfoFromViteRequest | null => {
    if (!req.url?.endsWith("index.html") || !req.originalUrl) {
        return null;
    }

    if (req.originalUrl && req.originalUrl.endsWith("devtools.json")) {
        return null;
    }

    const parsedUrl = url.parse(req.originalUrl);
    const [routeName, runUuid] = _.compact(parsedUrl.pathname?.split("/"));

    if (runUuid?.endsWith(".map")) {
        return null;
    }

    if (routeName !== VITE_RUN_UUID_ROUTE || !runUuid) {
        const lines: string[] = [];
        lines.push(`What happened: An incoming Vite request has an unexpected URL format: ${req.originalUrl}`);
        lines.push(`\nExpected format: /${VITE_RUN_UUID_ROUTE}/:uuid`);
        lines.push("\nPossible reasons:");
        lines.push("  - The browser navigated to an unexpected URL that is not managed by Testplane");
        lines.push("  - A middleware or proxy is rewriting the URL before it reaches Testplane's Vite server");
        lines.push("\nWhat you can do:");
        lines.push(
            `  - Make sure 'baseUrl' in your testplane config points to the Vite server root (e.g. http://localhost:5173)`,
        );
        lines.push("  - Check for any reverse proxy rules that may modify incoming request URLs");
        throw new Error(lines.join("\n"));
    }

    const env = WORKER_ENV_BY_RUN_UUID.get(runUuid);
    if (!env) {
        const lines: string[] = [];
        lines.push(`What happened: Worker environment was not found for run UUID "${runUuid}".`);
        lines.push("\nPossible reasons:");
        lines.push('  - The "runUuid" was not generated by Testplane (external request or stale browser tab)');
        lines.push("  - The test has already completed and the environment was cleaned up");
        lines.push("  - The worker process disconnected before the browser could connect");
        lines.push("\nWhat you can do:");
        lines.push(
            "  - Ensure no external process or browser tab is sending requests to the Vite server during test runs",
        );
        lines.push("  - Check for test timeout issues that may cause the worker to disconnect prematurely");
        throw new Error(lines.join("\n"));
    }

    return {
        routeName,
        runUuid,
        env: {
            ...env,
            file: path.posix.join("/", path.relative(process.cwd(), env.file).replaceAll(path.sep, path.posix.sep)),
        },
    };
};

export const getPathWithoutExtName = (fsPath: string): string => {
    const extname = path.extname(fsPath);

    if (!extname) {
        return fsPath;
    }

    return fsPath.slice(0, -extname.length);
};
